import { baseDeployToggles, contosoDeployTogglesType,resourceIdType,baseExistingVNetSubnetsDefinitionType } from 'common/types.bicep'

param deployToggles baseDeployToggles
param contosoToggles contosoDeployTogglesType
param resourceIds resourceIdType

var deployAppService = contosoToggles.?appService ?? false
@description('Optional. Location')
param location string = 'swedencentral'

@description('Optional.  Deterministic token for resource names; auto-generated if not provided.')
param resourceToken string = toLower(uniqueString(subscription().id, resourceGroup().name, location))

@description('Optional.  Base name to seed resource names; defaults to a 12-char token.')
param baseName string = substring(resourceToken, 0, 12)


// param subnets baseExistingVNetSubnetsDefinitionType 

// Reference the base AILZ infrastructure via file system
// This references the deploy/main.bicep generated by preprovision.sh
// which includes all template spec references for wrappers
// 
// This approach allows publishing platform/infra/contoso/main.bicep as a single
// Template Spec that workload teams can consume without ACR access
module baseInfra '../../../bicep/deploy/main.bicep' = {
  name: 'ailz-base-infrastructure'
  params: {
    deployToggles: deployToggles
    resourceIds: resourceIds
    // existingVNetSubnetsDefinition: subnets
    location: location
  }
}

// Alternative: Reference from ACR (requires ACR access for workload teams)
// Uncomment this and comment out the file reference above if using ACR approach
// module baseInfra 'br/ContosoACR:bicep/ailz/base:v20251106-cb61bb7' = {
//   name: 'ailz-base-infrastructure'
//   params: {
//     deployToggles: deployToggles
//     resourceIds: resourceIds
//     location: location
//   }
// }

// Contoso-specific resources below. Re-use Wrapper pattern?
module serverfarm 'br/public:avm/res/web/serverfarm:0.5.0' = if (deployAppService) {
  name: 'serverfarmDeployment'
  params: {
    // Required parameters
    name: 'appsvc-${baseName}'
    // Non-required parameters
    reserved: true
    skuName: 'FC1'
    tags: {
      Environment: 'Non-Prod'
      'hidden-title': 'This is visible in the resource name'
      Role: 'DeploymentValidation'
    }
    zoneRedundant: false
  }
}
module website 'br/public:avm/res/web/site:0.19.4' = if (deployAppService) {
  name: 'siteDeployment'
  params: {
    // Required parameters
    kind: 'app'
    name: baseName
    serverFarmResourceId: serverfarm.outputs.resourceId
    // Non-required parameters
    basicPublishingCredentialsPolicies: [
      {
        allow: false
        name: 'ftp'
      }
      {
        allow: false
        name: 'scm'
      }
    ]
    httpsOnly: true
    outboundVnetRouting: {
      allTraffic: true
      contentShareTraffic: true
      imagePullTraffic: true
    }
    publicNetworkAccess: 'Disabled'
    scmSiteAlsoStopped: true  
    siteConfig: {
      alwaysOn: false
      ftpsState: 'FtpsOnly'
      healthCheckPath: '/healthz'
      metadata: [
        {
          name: 'CURRENT_STACK'
          value: 'dotnetcore'
        }
      ]
      minTlsVersion: '1.2'
    }
  }
}
