import { baseDeployToggles, contosoDeployTogglesType,resourceIdType,baseExistingVNetSubnetsDefinitionType } from 'common/types.bicep'

param deployToggles baseDeployToggles
param contosoToggles contosoDeployTogglesType
param resourceIds resourceIdType

var deployAppService = contosoToggles.?appService ?? false
var deploySql = contosoToggles.?azureSql ?? false

@description('Optional. Location')
param location string = 'swedencentral'

@description('Optional.  Deterministic token for resource names; auto-generated if not provided.')
param resourceToken string = toLower(uniqueString(subscription().id, resourceGroup().name, location))

@description('Optional.  Base name to seed resource names; defaults to a 12-char token.')
param baseName string = substring(resourceToken, 0, 12)


// param subnets baseExistingVNetSubnetsDefinitionType 

// ===================================
// CONTOSO CUSTOM NSGS
// ===================================

// SQL Subnet NSG
module sqlNsg 'br/public:avm/res/network/network-security-group:0.5.0' = if (deploySql) {
  name: 'nsg-sql-${baseName}'
  params: {
    name: 'nsg-sql-${baseName}'
    location: location
    securityRules: [
      {
        name: 'AllowVnetInbound'
        properties: {
          protocol: '*'
          sourcePortRange: '*'
          destinationPortRange: '*'
          sourceAddressPrefix: 'VirtualNetwork'
          destinationAddressPrefix: '*'
          access: 'Allow'
          priority: 100
          direction: 'Inbound'
        }
      }
      {
        name: 'DenyAllInbound'
        properties: {
          protocol: '*'
          sourcePortRange: '*'
          destinationPortRange: '*'
          sourceAddressPrefix: '*'
          destinationAddressPrefix: '*'
          access: 'Deny'
          priority: 4096
          direction: 'Inbound'
        }
      }
    ]
  }
}

// App Service Subnet NSG
module appServiceNsg 'br/public:avm/res/network/network-security-group:0.5.0' = if (deployAppService) {
  name: 'nsg-appservice-${baseName}'
  params: {
    name: 'nsg-appservice-${baseName}'
    location: location
    securityRules: [
      {
        name: 'AllowAppServiceManagement'
        properties: {
          protocol: 'Tcp'
          sourcePortRange: '*'
          destinationPortRanges: ['454', '455']
          sourceAddressPrefix: 'AppServiceManagement'
          destinationAddressPrefix: '*'
          access: 'Allow'
          priority: 100
          direction: 'Inbound'
        }
      }
      {
        name: 'AllowVnetInbound'
        properties: {
          protocol: '*'
          sourcePortRange: '*'
          destinationPortRange: '*'
          sourceAddressPrefix: 'VirtualNetwork'
          destinationAddressPrefix: '*'
          access: 'Allow'
          priority: 200
          direction: 'Inbound'
        }
      }
    ]
  }
}

// ===================================
// CONTOSO CUSTOM SUBNETS
// ===================================

var contosoSubnets = concat(
  deploySql ? [{
    name: 'snet-sql'
    addressPrefix: '192.168.1.64/27'  // 32 IPs (192.168.1.64-95)
    networkSecurityGroupResourceId: sqlNsg.outputs.resourceId
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
  }] : [],
  deployAppService ? [{
    name: 'snet-appservice'
    addressPrefix: '192.168.1.96/27'  // 32 IPs (192.168.1.96-127)
    networkSecurityGroupResourceId: appServiceNsg.outputs.resourceId
    delegation: 'Microsoft.Web/serverFarms'
    privateEndpointNetworkPolicies: 'Disabled'
    privateLinkServiceNetworkPolicies: 'Enabled'
  }] : []
) 

// Reference the base AILZ infrastructure via file system
// This references the deploy/main.bicep generated by preprovision.sh
// which includes all template spec references for wrappers
// 
// This approach allows publishing platform/infra/contoso/main.bicep as a single
// Template Spec that workload teams can consume without ACR access
module baseInfra '../../../bicep/deploy/main.bicep' = {
  name: 'ailz-base-infrastructure'
  params: {
    deployToggles: deployToggles
    resourceIds: resourceIds
    location: location
    // Don't pass vNetDefinition - let upstream create default VNet with all default subnets
    // We'll add custom subnets in a separate module after VNet is created
  }
}

// Alternative: Reference from ACR (requires ACR access for workload teams)
// Uncomment this and comment out the file reference above if using ACR approach
// module baseInfra 'br/ContosoACR:bicep/ailz/base:v20251106-cb61bb7' = {
//   name: 'ailz-base-infrastructure'
//   params: {
//     deployToggles: deployToggles
//     resourceIds: resourceIds
//     location: location
//   }
// }

// ===================================
// ADD CUSTOM SUBNETS TO AILZ VNET
// ===================================

// Add custom subnets to the VNet created by AILZ
module customSubnets '../../../bicep/infra/helpers/deploy-subnets-to-vnet/main.bicep' = if (deploySql || deployAppService) {
  name: 'custom-subnets-${baseName}'
  params: {
    virtualNetworkName: last(split(baseInfra.outputs.virtualNetworkResourceId, '/'))
    subnets: contosoSubnets
  }
  dependsOn: [
    baseInfra
  ]
}

// ===================================
// CONTOSO RESOURCES - AZURE SQL
// ===================================

module sqlServer 'br/public:avm/res/sql/server:0.9.0' = if (deploySql) {
  name: 'sql-${baseName}'
  params: {
    name: 'sql-${baseName}'
    location: location
    // Azure AD-only authentication (required by policy)
    administrators: {
      azureADOnlyAuthentication: true
      login: 'SQL Admins'  // Azure AD group or user display name
      sid: '00000000-0000-0000-0000-000000000000'  // TODO: Replace with your Azure AD group/user object ID
      principalType: 'Group'  // or 'User'
      tenantId: subscription().tenantId
    }
    publicNetworkAccess: 'Disabled'
    minimalTlsVersion: '1.2'
    
    databases: [
      {
        name: 'db-contoso'
        skuName: 'Basic'
        skuTier: 'Basic'
      }
    ]
    
    managedIdentities: {
      systemAssigned: true
    }
  }
  dependsOn: [
    baseInfra  // Wait for VNet to be created
  ]
}

// SQL Private Endpoint
module sqlPrivateEndpoint 'br/public:avm/res/network/private-endpoint:0.9.0' = if (deploySql) {
  name: 'pe-sql-${baseName}'
  params: {
    name: 'pe-sql-${baseName}'
    location: location
    // Use AILZ private endpoint subnet
    subnetResourceId: '${baseInfra.outputs.virtualNetworkResourceId}/subnets/snet-privateendpoints'
    
    privateLinkServiceConnections: [
      {
        name: 'sql-connection'
        properties: {
          privateLinkServiceId: sqlServer.outputs.resourceId
          groupIds: ['sqlServer']
        }
      }
    ]
    
    // TODO: Integrate with AILZ-managed Private DNS Zone if available
    customNetworkInterfaceName: 'nic-pe-sql-${baseName}'
  }
}

// ===================================
// CONTOSO RESOURCES - APP SERVICE
// ===================================
// ===================================
// CONTOSO RESOURCES - APP SERVICE
// ===================================

// App Service Plan
module serverfarm 'br/public:avm/res/web/serverfarm:0.5.0' = if (deployAppService) {
  name: 'serverfarmDeployment'
  params: {
    // Required parameters
    name: 'asp-${baseName}'
    // Non-required parameters
    reserved: false  // Windows
    skuName: 'P1v3'  // Premium V3 required for VNet integration
    skuCapacity: 2  // Minimum 2 workers required for zone redundancy
    tags: {
      Environment: 'Non-Prod'
      'hidden-title': 'Contoso App Service Plan'
      Role: 'DeploymentValidation'
    }
  }
}

module website 'br/public:avm/res/web/site:0.19.4' = if (deployAppService) {
  name: 'siteDeployment'
  params: {
    // Required parameters
    kind: 'app'
    name: 'app-${baseName}'
    serverFarmResourceId: deployAppService ? serverfarm.outputs.resourceId : ''
    
    // Non-required parameters
    location: location
    basicPublishingCredentialsPolicies: [
      {
        allow: false
        name: 'ftp'
      }
      {
        allow: false
        name: 'scm'
      }
    ]
    httpsOnly: true
    
    // VNet Integration for outbound traffic
    virtualNetworkSubnetResourceId: deployAppService ? '${baseInfra.outputs.virtualNetworkResourceId}/subnets/snet-appservice' : ''
    
    publicNetworkAccess: 'Disabled'
    scmSiteAlsoStopped: true  
    siteConfig: {
      alwaysOn: true
      ftpsState: 'FtpsOnly'
      healthCheckPath: '/healthz'
      metadata: [
        {
          name: 'CURRENT_STACK'
          value: 'dotnetcore'
        }
      ]
      minTlsVersion: '1.2'
      vnetRouteAllEnabled: true  // Force all traffic through VNet
      http20Enabled: true
      // SQL Connection String (using managed identity)
      connectionStrings: deploySql ? [
        {
          name: 'DefaultConnection'
          connectionString: 'Server=tcp:sql-${baseName}.database.windows.net,1433;Database=db-contoso;Authentication=Active Directory Managed Identity;'
          type: 'SQLAzure'
        }
      ] : []
    }
    
    managedIdentities: {
      systemAssigned: true
    }
  }
  dependsOn: [
    baseInfra
    sqlPrivateEndpoint  // Ensure SQL is accessible before app starts
  ]
}

// App Service Private Endpoint (for inbound HTTPS traffic)
module appServicePrivateEndpoint 'br/public:avm/res/network/private-endpoint:0.9.0' = if (deployAppService) {
  name: 'pe-app-${baseName}'
  params: {
    name: 'pe-app-${baseName}'
    location: location
    subnetResourceId: '${baseInfra.outputs.virtualNetworkResourceId}/subnets/snet-privateendpoints'
    
    privateLinkServiceConnections: [
      {
        name: 'appservice-connection'
        properties: {
          privateLinkServiceId: deployAppService ? website.outputs.resourceId : ''
          groupIds: ['sites']
        }
      }
    ]
    
    // TODO: Integrate with AILZ-managed Private DNS Zone if available
    customNetworkInterfaceName: 'nic-pe-app-${baseName}'
  }
}
